### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by jonathanR79** [pulponair/koken-xml-sitemap#10]
Hello,
In my sitemaps, all url are in http instead of https:
https://www.jr-photo.be/sitemap.xml

Is this an issue on my side or is this in the plugin?

Would there be an easy way to have the plugin write https everywhere instead of http?

Thanks a lot for that nice plugin

**Comment by pulponair** [comment]
I just take the url as it comes from the kocken item "URL" field which contains the url sheme already. Please double check your installation r you performing some kind of https enforcement?

**Comment by pulponair** [comment]
Closed due to inactivity
