### ISSUE TITLE
clean url

### ISSUE THREAD

**Issue by jonathanR79** [pulponair/koken-xml-sitemap#11]
Hello,

Please, would it be possible to have the sitemap populated with clean url that you can obtain use mod_rewrite instead of url containing index.php each time?

E.G:
https://www.jr-photo.be/albums/street-bw/
Instead of:
https://www.jr-photo.be/index.php?/albums/street-bw/

Thanks

**Comment by pulponair** [comment]
Hey,
actually it is like this already:
<loc>http://10.11.12.13/koken/albums/test-album/</loc>
<lastmod>2018-10-01</lastmod>
<changefreq>weekly</changefreq>
<priority>1.0</priority>

**Comment by pulponair** [comment]
Closed due to inactivity. Feel free to reopen if the issue still persists
