### ISSUE TITLE
HTTP 500

### ISSUE THREAD

**Issue by LIvewire18** [pulponair/koken-xml-sitemap#12]
First off, let me say thank you very much for your work on this project!

I have been trying to get this plugin to work, but to no avail. I have gone as far as temporarily disabling selinux and setting html directory to 777 without any luck. I still get HTTP error 500 whenever I try to access the sitemap.xml file (both via /sitemap.xml & index.php?sitemap.xml). 

Specs:
 
Centos 7.5.1804
Apache 2.4.6
PHP 7.2.7
Koken 0.22.24
Sitemap Plugin Version 2.2
Theme Axis-2

Already tried: (and reset all afterwards)

Setting permissions to 777 (reset to 755)
Disable selinux (re-enabled)
Removed .htaccess (standard .htaccess from install, no modifications except require https for admin uncommented)
Restarting Apache
Turned on/off various options in setup to include/exclude specific pages.
Turned on/off cache

Addditional Notes:

I run vhosts and I have checked the config file. The only settings currently set (build) are "AllowOverride All", "Require all granted" and "Options FollowSymLinks" along with DirectoryIndex index.html index.php. 

I have also looked in the /etc/httpd/logs/error_log and access_log. Nothing in there appeared to show any issues. The only thing in the error log was the normal /usr/local/ImageMagick/... No Such file or directory which is a false positive from what I have gathered. 

I do have a few other plugins installed, and they all appear to work properly. 

I have MemCached installed and mod_pagespeed, but not sure if that would cause any issues with the plugin. I have tried the file with "?ModPagespeed=off" and still received HTTP 500.

I hope you can help me out this. If you need more info, please let me know.

**Comment by pulponair** [comment]
Hey,
thanks for you feedback. I v to admit that i am not really working on this anymore but if you get an 500 error there should be a more detailed "error message" in the logfile. Without a detailed "message" i cant help you, i am sorry :/. 
cheers,
Nikolas

**Comment by pulponair** [comment]
If you run vhosts you probably v logfiles per vhost could you check for that please?

**Comment by pulponair** [comment]
Closed due to inactivity. Feel free to reopen if the issue still persists
