### ISSUE TITLE
Add additional line of code to include captions in XML

### ISSUE THREAD

**Issue by ragues** [pulponair/koken-xml-sitemap#5]
To add image captions, I've added the following additional line to my code after line 182

$imageChild->addChild('image:caption', $item['caption'], self::IMAGE_NS);

Could be of use to others if incorporated?

**Comment by elRafa** [comment]
This is great. Hopefully it'll get incorporated, but I have my doubts it will happen very soon since Koken is currently in the process of being sold:
http://blog.koken.me/essays/2015/08/koken-sale-update/

**Comment by pulponair** [comment]
hey, just fork and create a merge request :)

**Comment by ragues** [comment]
Thanks for the tip - done

**Comment by pulponair** [comment]
i added that in 2.2. Not sure if we should remove title and caption if they r empty. or maybe use the filename as title for fallback. What do you think

**Comment by pulponair** [comment]
ok done, what about the caption? leave the tag away if its empty? or render an empty tag?

**Comment by pulponair** [comment]
I removed the caption tag if the caption is empty that slows down global warming. Thing this issue can be closed.
