### ISSUE TITLE
Albums are not in sitemap

### ISSUE THREAD

**Issue by julienmtrazeo** [pulponair/koken-xml-sitemap#7]
Hi,
These are my settings (and the reason) :

- Exclude page : unchecked (I have one page and one or two more are to come)
- Exclude essays : checked (I don't use the Essays feature)
- Exclude albums : unchecked (I wan't to show my work, so thos are the main pages for me)
- Exclude content : checked (I don't want a direct access to the content)

The result in the sitemap is : 

- I see the page url (ok)
- I see the sets urls (great !)
- I don't see the albums url (too bad :()

Did I miss something in my settings ?
Is there a bug ?

Regards,

Julien

**Comment by pulponair** [comment]
Hey,
make sure the album contains at least one picutre or ever contained one (otherwise it wont be loaded by the koken api for whatever reasons - u wont even see it on the frontend).
cheers,
Nikolas

**Comment by pulponair** [comment]
Closed due to inactivity. Feel free to reopen if the issue still persists
